### ISSUE TITLE
Patch for /trunk/psicquic-registry/src/example/python/read-registry.py

### ISSUE THREAD

**Issue by noedelta** [PSICQUIC/psicquic-registry#1]
_From @GoogleCodeExporter on March 18, 2015 11:1_

```
Adding the codes for Win-Python 3.3
```

Original issue reported on code.google.com by `bioinfor...@gmail.com` on 1 May 2014 at 10:46

Attachments:
- [read-registry.py.patch](https://storage.googleapis.com/google-code-attachments/psicquic/issue-34/comment-0/read-registry.py.patch)

_Copied from original issue: MICommunity/psicquic#34_

**Comment by bblodfon** [comment]
Added examples in Python 3.x (develop branch of psicquic-registry-client module).

**Comment by bblodfon** [comment]
See previous comment :)
