### ISSUE TITLE
baderlab REST/SOAP services refusing connections despite being marked as active in registry

### ISSUE THREAD

**Issue by noedelta** [PSICQUIC/psicquic-registry#5]
_From @GoogleCodeExporter on March 18, 2015 11:1_

```



 http://webservice.baderlab.org:8180/psicquic-ws/webservices/current/search/query/brca2?format=tab25

 http://webservice.baderlab.org:8180/psi-gm/webservices/current/search/query/brca2?format=tab25

 http://www.baderlab.org:8180/psicquic-interoporc-ws/webservices/current/search/query/brca2?format=tab25



```

Original issue reported on code.google.com by `kenny.br...@gmail.com` on 1 Aug 2012 at 1:07

_Copied from original issue: MICommunity/psicquic#31_

**Comment by bblodfon** [comment]
This issue is now solved, since the BIND-related psicquic services are listed as INACTIVE in the registry.
